version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - Frankeo
  - mceledm
  assignees:
  - Frankeo
  labels:
  - dependencies
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.5
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: husky
    versions:
    - 5.0.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: console-table-printer
    versions:
    - 2.7.5
    - 2.8.1
    - 2.8.2
  - dependency-name: pinst
    versions:
    - 2.1.4
    - 2.1.6
  - dependency-name: sqlite3
    versions:
    - 5.0.1
    - 5.0.2
  - dependency-name: fs-extra
    versions:
    - 9.1.0
  - dependency-name: commitizen
    versions:
    - 4.2.3
