title: Interview Tool
email: ingfrancisco.moreno1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Official site for CLI Interview Tool
  Create, Save and Deploy exercises for interviews into codesandbox.
github_username:  Frankeo

# Build settings
theme: jekyll-theme-cayman
